"""add_password_hash_to_users

Revision ID: 4517dcc2e52b
Revises: 054ced276642
Create Date: 2026-02-06 05:32:40.216832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4517dcc2e52b'
down_revision: Union[str, Sequence[str], None] = '054ced276642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_tasks_id_user_id'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_user_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_tasks_user_id'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tasks_user_id'), 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.create_index(op.f('idx_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_index(op.f('idx_tasks_id_user_id'), 'tasks', ['id', 'user_id'], unique=False)
    # ### end Alembic commands ###
