apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-backend-secret
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.backend.env.DATABASE_URL | quote }}
  JWT_SECRET: {{ .Values.backend.env.JWT_SECRET | quote }}
  GEMINI_API_KEY: {{ .Values.backend.env.GEMINI_API_KEY | quote }}
