openapi: 3.0.3
info:
  title: Todo API - Authenticated Task Endpoints
  description: RESTful API for task management with JWT authentication and user isolation
  version: 1.0.0
  contact:
    name: API Support

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.example.com
    description: Production server

security:
  - BearerAuth: []

paths:
  /tasks:
    get:
      summary: Get all tasks for authenticated user
      description: Returns a list of all tasks belonging to the authenticated user
      operationId: getTasks
      tags:
        - Tasks
      parameters:
        - name: completed
          in: query
          description: Filter by completion status
          required: false
          schema:
            type: boolean
        - name: priority
          in: query
          description: Filter by priority level
          required: false
          schema:
            type: string
            enum: [low, medium, high]
      responses:
        '200':
          description: Successful response with list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
              example:
                - id: 1
                  user_id: "abc123"
                  title: "Complete project documentation"
                  description: "Write comprehensive docs for the API"
                  completed: false
                  priority: "high"
                  due_date: "2026-02-10T17:00:00Z"
                  created_at: "2026-02-05T10:00:00Z"
                  updated_at: "2026-02-05T10:00:00Z"
                - id: 2
                  user_id: "abc123"
                  title: "Review pull requests"
                  description: null
                  completed: true
                  priority: "medium"
                  due_date: null
                  created_at: "2026-02-04T14:30:00Z"
                  updated_at: "2026-02-05T09:15:00Z"
        '401':
          $ref: '#/components/responses/UnauthorizedError'

    post:
      summary: Create a new task
      description: Creates a new task for the authenticated user
      operationId: createTask
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
            example:
              title: "Implement JWT authentication"
              description: "Add middleware for token verification"
              priority: "high"
              due_date: "2026-02-08T17:00:00Z"
      responses:
        '201':
          description: Task created successfully
          headers:
            Location:
              description: URL of the created task
              schema:
                type: string
                example: /tasks/3
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: 3
                user_id: "abc123"
                title: "Implement JWT authentication"
                description: "Add middleware for token verification"
                completed: false
                priority: "high"
                due_date: "2026-02-08T17:00:00Z"
                created_at: "2026-02-05T11:00:00Z"
                updated_at: "2026-02-05T11:00:00Z"
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /tasks/{task_id}:
    get:
      summary: Get a specific task
      description: Returns a single task if it belongs to the authenticated user
      operationId: getTask
      tags:
        - Tasks
      parameters:
        - name: task_id
          in: path
          description: Task ID
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Successful response with task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

    put:
      summary: Update a task
      description: Updates a task if it belongs to the authenticated user
      operationId: updateTask
      tags:
        - Tasks
      parameters:
        - name: task_id
          in: path
          description: Task ID
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
            example:
              title: "Complete project documentation (updated)"
              completed: true
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

    delete:
      summary: Delete a task
      description: Deletes a task if it belongs to the authenticated user
      operationId: deleteTask
      tags:
        - Tasks
      parameters:
        - name: task_id
          in: path
          description: Task ID
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: Task deleted successfully (no content)
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token issued by Better Auth

  schemas:
    Task:
      type: object
      required:
        - id
        - user_id
        - title
        - completed
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          description: Unique task identifier
          example: 1
        user_id:
          type: string
          description: ID of the user who owns this task
          example: "abc123"
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Task title
          example: "Complete project documentation"
        description:
          type: string
          nullable: true
          maxLength: 2000
          description: Detailed task description
          example: "Write comprehensive docs for the API"
        completed:
          type: boolean
          description: Task completion status
          example: false
        priority:
          type: string
          nullable: true
          enum: [low, medium, high]
          description: Task priority level
          example: "high"
        due_date:
          type: string
          format: date-time
          nullable: true
          description: Task due date in ISO 8601 format
          example: "2026-02-10T17:00:00Z"
        created_at:
          type: string
          format: date-time
          description: Timestamp when task was created
          example: "2026-02-05T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: Timestamp when task was last updated
          example: "2026-02-05T10:00:00Z"

    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Task title
          example: "Implement JWT authentication"
        description:
          type: string
          nullable: true
          maxLength: 2000
          description: Detailed task description
          example: "Add middleware for token verification"
        priority:
          type: string
          nullable: true
          enum: [low, medium, high]
          description: Task priority level
          example: "high"
        due_date:
          type: string
          format: date-time
          nullable: true
          description: Task due date in ISO 8601 format
          example: "2026-02-08T17:00:00Z"

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Task title
          example: "Complete project documentation (updated)"
        description:
          type: string
          nullable: true
          maxLength: 2000
          description: Detailed task description
          example: "Write comprehensive docs for the API (updated)"
        completed:
          type: boolean
          description: Task completion status
          example: true
        priority:
          type: string
          nullable: true
          enum: [low, medium, high]
          description: Task priority level
          example: "medium"
        due_date:
          type: string
          format: date-time
          nullable: true
          description: Task due date in ISO 8601 format
          example: "2026-02-10T17:00:00Z"

    Error:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Human-readable error message
          example: "Authentication required"
        code:
          type: string
          description: Machine-readable error code
          example: "AUTHENTICATION_REQUIRED"

  responses:
    UnauthorizedError:
      description: Authentication required or token invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            missing_token:
              summary: Missing Authorization header
              value:
                detail: "Authentication required"
                code: "AUTHENTICATION_REQUIRED"
            invalid_token:
              summary: Invalid or expired token
              value:
                detail: "Invalid or expired token"
                code: "INVALID_TOKEN"

    NotFoundError:
      description: Task not found or user doesn't have permission
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Task not found or you don't have permission to access it"
            code: "TASK_NOT_FOUND"

    ValidationError:
      description: Request validation failed
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: array
                items:
                  type: object
                  properties:
                    loc:
                      type: array
                      items:
                        type: string
                      description: Location of the error (field path)
                    msg:
                      type: string
                      description: Error message
                    type:
                      type: string
                      description: Error type
          example:
            detail:
              - loc: ["body", "title"]
                msg: "field required"
                type: "value_error.missing"
              - loc: ["body", "priority"]
                msg: "value is not a valid enumeration member; permitted: 'low', 'medium', 'high'"
                type: "type_error.enum"
